#!/bin/bash
cd "$( dirname "$0" )"
RUN_AS_ROOT=no
RELOAD_PARAM=""
case "$( tr A-Z a-z <<<"$DEV_MODE" )" in
    y|yes|1)
        RELOAD_PARAM=--reload
        RUN_AS_ROOT=yes
        ;;
esac

if [ "$RUN_AS_ROOT" == no ] && [ "$EUID" == 0 ]; then
    cat >&2 <<EOF
Error: running StarQuew as root is not recommended.
Please start StarQuew as normal user (see docs on https://github.com/GuLinux/StarQuew).
EOF
    exit 1
fi
if [ "$1" == --check-user ]; then
    exit 0
fi

export VENV_HOME="$HOME/.local/share/StarQuew/python-venv"
if [ ! -d "$VENV_HOME" ]; then
    mkdir -p "$( dirname "$VENV_HOME" )"
    python3 -m venv "$VENV_HOME"
fi

. "$VENV_HOME/bin/activate"

requirements_checksum="$( md5sum requirements.txt | cut -d' ' -f1 )"
if [ "$requirements_checksum" != "$( cat "$VENV_HOME/requirements_checksum" 2>/dev/null )" ]; then
    pip install wheel # prerequisite for installing other packages
    pip install -r requirements.txt || exit $?
fi
echo "$requirements_checksum" > "$VENV_HOME/requirements_checksum"

native_image_processor_checksum="$( md5sum image_processing/image_processing.{h,cpp} | cut -d' ' -f1 | tr '\n' '-' )"
if [ "$native_image_processor_checksum" != "$( cat "$VENV_HOME/native_image_processor_checksum" 2>/dev/null )" ]; then
    bash ./image_processing/compile || exit $?
fi
echo "$native_image_processor_checksum" > "$VENV_HOME/native_image_processor_checksum"

if [ "$1" == --only-deps ]; then
    exit 0
fi

export PYTHONPATH="$PWD/indi-lite-tools/:$PWD:$HOME/.local/share/StarQuew/native_modules:$PYTHONPATH"
gunicorn --threads ${WEB_THREADS:-4} ${RELOAD_PARAM} -t 30 -k gthread -b 0.0.0.0:5000 star-quew:app "$@"
