#!/bin/bash

find_binary() {
    which "$1" >/dev/null 2>&1
}

exit_error() {
    echo "$@" >&1
    exit 1
}

if find_binary openbox; then
    openbox &
else
     exit_error "Unable to find window manager [openbox]"
fi

phd2

