version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mkdir build
      - run: cd build
      - run: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCONFDIR=/etc
      - run: make package
      - store_artifacts:
          path: ~/repo/build/StarQuew-*
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
