version: 2
jobs:
  build:
    branches:
        only:
            - master
    docker:
      - image: gulinux/starquew-circleci
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "frontend/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCONFDIR=/etc && make package && rm -rf packages/_CPack_Packages
      - store_artifacts:
          path: ~/repo/build/packages
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null marco@gulinux.net -p 8122 ./starquew-publish -b $CIRCLE_BUILD_NUM -d $CIRCLE_COMPARE_URL -r $CIRCLE_REPOSITORY_URL -c $CIRCLE_SHA1
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "frontend/package.json" }}
