#!/bin/bash
scriptdir="$( dirname "$0")"
cd "$scriptsdir"
echo "Working directory: $PWD"

if ! [ -r "$HOME/github_access_token" ]; then
    echo "The file $HOME/github_access_token must be present to read credentials" >&2
    exit 1
fi

if ! [ -d "venv" ]; then
	python3 -m venv "venv"
fi
. "venv/bin/activate"

. "$HOME/github_access_token"

pip3 install -r "requirements.txt"

if ./check-release.py; then
	exit 0
fi

./raspbian-gen -d -r && python3 ./deploy-image-release.py

