#!/bin/bash

project_dir="$( cd "$( dirname "$0")/../.."; pwd)"
raspbian_gen_root="$( cd "$( dirname "$0")"; pwd )"
rpigen_path="$raspbian_gen_root/pi-gen"

launcher_script="$raspbian_gen_root/files/provisioning-launcher"
provisioning_script="$project_dir/scripts/setup/ubuntu-raspbian.sh"
copy_script="$raspbian_gen_root/files/copy-provisioning"

USE_QEMU=0
DEPLOY_ZIP=0
USE_DOCKER=0
CONTINUE=""

show_help() {
    cat >&2 <<EOF
Usage: $0 [options].
Available options:

 -q|--qemu      create a Qemu image for testing
 -r|--rm        remove and rebuild the docker image
 -c|--continue  continue a stopped build
 -z|--zip       zip the destination file
 -d|--docker    use docker to build image
 --remove-pigen remove pi-gen repository
EOF
    exit "${1:-1}"
}

while [ -n "$1" ]; do
    case "$1" in
        -q|--qemu)
            USE_QEMU=1
            ;;
        -r|--rm)
            docker rm -v pigen_work
            ;;
        -c|--continue)
            CONTINUE=1
            ;;
        --remove-pigen)
            rm -rf $rpigen_path
            ;;
        -z|--zip)
            DEPLOY_ZIP=1
            ;;
        -d|--docker)
            USE_DOCKER=1
            ;;
        *)
            show_help
            ;;
    esac
    shift
done

if ! [ -d "$rpigen_path" ]; then
    git clone https://github.com/RPi-Distro/pi-gen
fi

cd "$rpigen_path"
git checkout -f master
git clean -f -d -x
git pull

sudo modprobe loop

cat > config <<EOF
IMG_NAME="AstroPhoto-Plus"
FIRST_USER_NAME="stargazer"
FIRST_USER_PASS="AstroPhoto-Plus"
ENABLE_SSH=1
DEPLOY_ZIP=$DEPLOY_ZIP
USE_QEMU=${USE_QEMU}
#STAGE_LIST="stage2"
STAGE_LIST="stage0 stage1 stage2"
EOF

mkdir -p stage2/99-install-astrophotoplus/files

cp -v "$provisioning_script" stage2/99-install-astrophotoplus/files/provisioning.sh
cp -v "$copy_script" stage2/99-install-astrophotoplus/00-run.sh
cp -v "$launcher_script" stage2/99-install-astrophotoplus/01-run-chroot.sh
sed -i 's/-lite//g' "stage2/EXPORT_IMAGE"

if [ "$USE_DOCKER" == 1 ]; then
    CONTINUE="$CONTINUE" ./build-docker.sh
else
    CONTINUE="$CONTINUE" ./build.sh
fi

