#!/bin/bash
set -e
set -x
# Old stuff, it should be obsolete by now with the new start-server
# requirements_checksum="$( md5sum requirements.txt | cut -d' ' -f1 )"
# last_requirements_checksum_file="/usr/local/lib/python3.6/dist-packages/last_requirements_checksum"
# if [ "$requirements_checksum" != "$( cat "$last_requirements_checksum_file" 2>/dev/null )" ]; then
#     pip3 install -r requirements.txt
# fi
# echo "$requirements_checksum" > "$last_requirements_checksum_file"
ACCESS_LOG_FILE=/tmp/access.log ./start-debug-server
