version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
        - "${EXTERNAL_WEB_PORT}:80"
    volumes:
        - ./nginx-conf.d:/etc/nginx/conf.d:ro
    depends_on:
        - frontend
        - backend
  frontend:
    build: frontend
    volumes:
        - ../../frontend:/app
        - node_modules:/app/node_modules
    expose:
        - "3000"
  backend:
    build: backend
    volumes:
        - ../../backend:/app
    expose:
        - "5000"
    environment:
        - INDI_SERVER_HOST
        - INDI_SERVER_PORT
        - WEB_THREADS
        - REDIS_SERVER=redis
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
volumes:
    node_modules:
