#!/bin/bash
set -e
set -x
pip3 install -r requirements.txt
case "$DEV_BACKEND_SERVER" in
    flask)
        flask run -h 0.0.0.0 --with-threads
        ;;
    gunicorn)
        gunicorn --threads $WEB_THREADS -t 999999 -k $GUNICORN_WORKER_CLASS -b 0.0.0.0:5000 star-quew:app
        ;;
    *)
        echo "Backend $DEV_BACKEND_SERVER not supported; exiting" >&2
        exit 1
esac
