#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0" )"; pwd )"

setup_wifi_ap() {
    [[ -z "$AP_ESSID" ]] && AP_ESSID="$HOSTNAME"
    [[ -r /etc/hostapd/.wifi_setup ]] && . /etc/hostapd/.wifi_setup
    read -p "Enter your wifi access point ESSID: " -i "$AP_ESSID" -e AP_ESSID
    read -p "Enter your wifi access point secret: " -i "$AP_SECRET" -e AP_SECRET
    cp "$SCRIPT_PATH/"wifi-ap/ap-mode /usr/local/bin/
    cp "$SCRIPT_PATH/"wifi-ap/dhcpcd.conf-ap-* "$SCRIPT_PATH/"wifi-ap/dnsmasq.conf /etc/
    cp "$SCRIPT_PATH/"wifi-ap/interfaces-ap-* /etc/network/
    cp "$SCRIPT_PATH/"wifi-ap/hostapd.conf /etc/hostapd/
    cp "$SCRIPT_PATH/"wifi-ap/hostapd /etc/default/
    [[ -n "$AP_ESSID" ]] && sed -i "s^___WPA_PASSPHRASE___^$AP_SECRET^g" /etc/hostapd/hostapd.conf
    [[ -n "$AP_SECRET" ]] && sed -i "s^___ESSID___^$AP_ESSID^g" /etc/hostapd/hostapd.conf
    cat >/etc/hostapd/.wifi_setup <<EOF
export AP_SECRET="$AP_SECRET"
export AP_ESSID="$AP_ESSID"
EOF
    echo "To activate and deactivate wifi access point (only for wlan0), just run ap-mode enable/disable"
}


install_debian_ubuntu() {
    apt install -y hostapd dnsmasq
}

install_arch_linux() {
    pacman -S hostapd dnsmasq
}

case "$1" in
    debian|ubuntu)
        install_debian_ubuntu
        setup_wifi_ap
        ;;
    arch-linux)
        install_arch_linux
        setup_wifi_ap
        ;;
    *)
        cat >&2 <<EOF
Usage: $0 <distribution>
Valid distributions:
  - debian
  - ubuntu
  - arch-linux
EOF
    exit 1
    ;;
esac
