#!/bin/bash
propname='ZWO CCD ASI183MM Pro.CCD_TEMPERATURE.CCD_TEMPERATURE_VALUE'
read_temp() {
    indi_getprop -1 "$propname" 
}

temp_is() {
    target="$1"
    [ "$( read_temp )" == "$target" ]
}

temp="$1"

if [ -z "$temp" ] || [ "$temp" -lt -40 ]; then
    echo "Usage: $0 temperature"
    exit 1
fi

echo -n "Setting temperature to $temp"
indi_setprop "$propname=$temp"

while ! temp_is "$temp"; do
    echo -n "."
    sleep 1
done

echo " done!"
