#!/bin/bash

set -e

RELEASES_URL="https://api.github.com/repos/GuLinux/AstroPhoto-Plus/releases"

get-installed-version() {
    dpkg-query --showformat='${Version}' --show astrophotoplus
}

get-latest-info() {
    curl -L -f -s "$RELEASES_URL"
}

get-latest-deb() {
    dpkg -s python3-requests >/dev/null 2>&1 || sudo apt install -y python3-requests
    python3 - <<EOF
import requests
import json

def is_compatible_asset(asset):
    if not asset['name'].endswith('.deb'):
        return False
    if '$( lsb_release -si)' == 'Raspbian':
        return 'Raspbian' in asset['name']
    return 'Raspbian' not in asset['name']

latest_version = requests.get('$RELEASES_URL')
latest_version_info = sorted(latest_version.json(), key=lambda r: r['created_at'], reverse=True)[0]
deb_asset = [asset for asset in latest_version_info['assets'] if is_compatible_asset(asset)]
print(deb_asset[0]['browser_download_url'])
EOF
}

needs-update() {
    python3 - <<EOF
current_version = '$( get-installed-version)'

if not current_version:
    raise RuntimeError('Unable to detect installed version')

latest = '$( basename "$1")'

if latest.startswith('AstroPhotoPlus-{}'.format(current_version)):
    print('is_latest')
else:
    print('needs_update')

EOF
}

run-updater() {
    echo "Updating to package $@"
    temp_deb_file="/tmp/$( basename "$1")"
    cd /tmp
    curl -L "$1" -o "$temp_deb_file"
    apt install -y "$temp_deb_file"
    rm -f "$temp_deb_file"
    echo "Your system will now reboot."
    AstroPhotoPlus-ctl restart
}


update() {
    latest_deb="$( get-latest-deb )"
    if [ "$(needs-update "$latest_deb")" == "is_latest" ]; then
        echo "Already at latest version"
    else
        echo "New version found! Updating..."
        run-updater "$latest_deb"
    fi
}

case "$1" in
    update)
        update
        ;;
    get-latest-info)
        get-latest-info
        ;;
    *)
        echo "Usage: $0 update|get-latest-info" >&1
        exit 1
        ;;
esac

